### PR TITLE
Cleaned order methods + bugfixing of order methods

### PR DESCRIPTION
**Pull request by martijndierckx**

### CODE REVIEW

**Comment by martijndierckx** [comment]
Thanks for cleaning up the code.
I readded the direct order method, since IMHO you need to be able to place orders on an ID basis. Not only via a search.

**Comment by pladaria** [comment]
Hi,

Sorry for the delay, I've been really busy those days. There are many conflicts in merge, would you mind to update your branch with master and fix them?

**Comment by pladaria** [comment]
I'm going to completely remove buy and sell methods.

I've merged your branch, I'm doing some cleanup, documenting and trying to solve an authentication related problem. For some reason it fails when placing an order, although the login and the session is correct. Perhaps they changed something in the API

**Comment by pladaria** [comment]
The problem was the url, it is `/secure/v5` instead of `/secure_s/v5`.

Can you confirm? Maybe different users have different URLs

**Comment by pladaria** [comment]
I've published v2.0.0 because it includes breaking changes. During the next days I will try to write some end-to-end automated tests to quickly check all features.

Thanks for you collaboration

**Comment by martijndierckx** [comment]
I've checked some things and as far as I can see, the URLs are as follows:
trading_s/secure/v5/checkOrder
trading_s/secure/v5/order

So I believe you are correct

**Pull request merged**
